name: Build OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare
    runs-on: [ Windows ]
    steps:  
      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Get dependency version
        shell: cmd
        run: |
          perl --version
          nasm --version
      
  build:
    name: Build OpenSSL
    needs: [ prepare ]
    runs-on: [ Windows ]
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'circle81918/build_openssl'
          submodules: recursive

      - name: Build
        shell: cmd
        working-directory: circle81918\build_openssl
        run: build.bat ${{ matrix.arch }}

      - name: Prepare Artifact
        shell: powershell
        working-directory: circle81918\build_openssl\openssl
        run: prepareArtifact.ps1 ${{ matrix.arch }}

  create_release:
    name: Create Release
    if: github.ref == 'refs/heads/master'
    needs: [ prepare ]
    runs-on: [ Windows ]
    steps:
      - name: Get OpenSSL version
        id: get_version
        shell: powershell
        run: |
          [string[]]$version = Get-Content -Path .\VERSION.dat | Select-String MAJOR, MINOR, PATCH
          $number = $version[0].Split("=")[-1] + "." + $version[1].Split("=")[-1] + "." + $version[2].Split("=")[-1] 
          echo "version=$number" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
      
