name: Build OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare
    runs-on: [ Windows ]
    steps:  
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Get nasm version
        shell: cmd
        run: nasm --version