name: Build OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare
    runs-on: [ Windows ]
    steps:  
      - name: Get dependency version
        shell: cmd
        run: |
          perl --version
          nasm --version
      
#  build:
#    name: Build OpenSSL
#    needs: [ prepare ]
#    runs-on: [ Windows ]
#    strategy:
#      matrix:
#        arch: [x86]

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          path: 'circle81918/build_openssl'
#          submodules: recursive

#      - name: Build
#        shell: cmd
#        working-directory: circle81918\build_openssl
#        run: build.bat ${{ matrix.arch }}

#      - name: Prepare Artifact
#        shell: powershell
#        working-directory: circle81918\build_openssl
#        run: .\prepareArtifact.ps1 ${{ matrix.arch }}

  create_release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    needs: [ prepare ]
    runs-on: [ Windows ]
    steps:
      - name: Get OpenSSL version
        id: get_version
        shell: powershell
        working-directory: circle81918\build_openssl\openssl
        run: |
          [string[]]$version = Get-Content -Path .\VERSION.dat | Select-String MAJOR, MINOR, PATCH
          $number = $version[0].Split("=")[-1] + "." + $version[1].Split("=")[-1] + "." + $version[2].Split("=")[-1]
          echo "::set-output name=version::$number"

      - name: Create Release
        id: create_release
        shell: powershell
        working-directory: circle81918\build_openssl\
        run: hub release create -m "${{ steps.get_version.outputs.version }}" "${{ steps.get_version.outputs.version }}"

      - name: Upload Release Asset
        id: upload-release-asset
        shell: powershell
        working-directory: circle81918\build_openssl\openssl
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: >
          hub release edit
          -a ".\output\x86\openssl_x86.zip"
          "${{ steps.get_version.outputs.version }}"
