name: Build OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare
    runs-on: [ Windows ]
    steps:  
      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Get dependency version
        shell: cmd
        run: |
          perl --version
          nasm --version
      
  build:
    name: Build OpenSSL
    needs: [ prepare ]
    runs-on: [ Windows ]
    strategy:
      matrix:
        arch: [amd64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'circle81918/build_openssl'
          submodules: recursive
      
      - name: Set VC config
        shell: cmd
        run: vcvarsall.bat ${{ matrix.arch }}
      
      - name: Set perl config
        run: perl Configure VC-WIN32

      - name: Build
        run: |
          nmake
          nmake test
          nmake install
      
