name: Build OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare
    runs-on: [ Windows ]
    steps:  
      - name: Install NASM
        uses: ilammy/setup-nasm@v1

      - name: Get dependency version
        shell: cmd
        run: |
          perl --version
          nasm --version
      
  build:
    name: Build OpenSSL
    needs: [ prepare ]
    runs-on: [ Windows ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'circle81918/build_openssl'
          token: ${{ secrets.REPO_TOKEN }}
          submodules: recursive
